language: minimal
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
    - conda env create --name mkpy -f conda/environment.yml
    - source activate mkpy
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
    - pip install black
    # install mkpy locally to build Cython and to import into notebooks
    - pip install -e .
script:
    - black --check --verbose --line-length=79 .
    - pytest --disable-warnings --cov=mkpy  # else mkpy warnings clog output
after_success:
    - pip install codecov && codecov
before_deploy:
    - pip install sphinx sphinx_rtd_theme jupyter nbsphinx nbconvert!=5.4
    - conda install -c conda-forge pandoc
    - conda list
    - cd mkpy/docs
    - sphinx-apidoc -f -e -o source .. test/*
    - make html
    - touch _build/html/.nojekyll
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep-history: true
    on:
        branch: master
    target_branch: gh-pages  # that's the default anyway, just to be explicit
    local_dir: mkpy/docs/_build/html
