# mkpy requires a current GIT_TOKEN on TravisCI kutaslab/mkpy
env:
    - PACKAGE_NAME: mkpy   # for the conda_upload.sh deploy script
language: minimal
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - source $HOME/miniconda/etc/profile.d/conda.sh && conda activate
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda info -a
install:
    - conda install -q conda-build conda-verify
    - conda build conda -c defaults -c conda-forge
    - conda create --name mkpy_env mkpy -c local -c defaults -c conda-forge
    - conda activate mkpy_env  # so tests run in env as installed by conda
    - conda install black pytest-cov
    - conda list
    - lscpu
    - python -c 'import numpy; numpy.show_config()'
    - python -c 'import mkpy'
    - python -c 'from mkpy import _mkh5'
    - python -c 'from mkpy import mkh5'

script:
    - black --check --verbose --line-length=79 .
    - pytest --disable-warnings --cov=mkpy
after_success:
    - pip install codecov && codecov
before_deploy:
    - pip install sphinx sphinx_rtd_theme jupyter nbsphinx nbconvert!=5.4
    - conda install -c conda-forge pandoc
    - conda install anaconda-client
    - conda list
    - sphinx-apidoc -e -f -o mkpy/docs/source/ mkpy ./tests/ ./mkpy/dpath/* ./setup.py
    - make -C mkpy/docs html
    - touch mkpy/docs/_build/html/.nojekyll
deploy:
    - provider: script
      skip_cleanup: true
      script: bash ./scripts/conda_upload.sh
      on:
          all_branches: true

    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep-history: true
      on:
          # branch: master
          all_branches: true
      target_branch: gh-pages  # that's the default anyway, just to be explicit
      local_dir: mkpy/docs/_build/html

