# build cmd from parent dir: conda-build -c defaults -c conda-forge conda

package:
  name: mkpy
  version: "0.1.3"

# source:
#   path: ../
source:
  git_url: https://github.com/kutaslab/mkpy.git
  # git_rev: 0.1.3
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - numpy
    - setuptools
    - Cython

  run:
    - python
    - numpy
    - h5py
    - matplotlib
    - pandas
    - pyarrow
    - PyYAML
    - xlrd
    - yamllint

test:
  imports:
    - mkpy

about:
  home: https://github.com/kutaslab/mkpy
  license: BSD
  license_file: LICENSE
