{% set data = load_setup_py_data() %}

# legacy pins for reference mkpy <=0.2.3
# {% set np_pin = "1.16.4" %}
# {% set py_pin = "3.6" %}

package:
  name: mkpy
  version: {{ data.get('version') }}

source:
  # path: ../
  git_url: ../  # to enable GIT_X_Y env vars

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: py{{environ.get("CONDA_PY", "XX")}}{{environ.get("GIT_ABBREV_COMMIT", "no_git_abbrev_commit") }}_{{ environ.get("PKG_BUILDNUM", "no_pkg_buildnum") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - setuptools
    - cython
    - numpy
  run:
    - python {{ python }}
    - numpy
    - h5py
    - matplotlib
    - pandas >=1.0
    - pytables
    - pyarrow >=1.0,!=1.0.1  # release fights with pandas
    - xlrd
    - PyYAML
    - yamllint
    - pytest  !=5.3.4 # so users can run tests, bad release fights with nose
    - nose  # for legacy dpath tests
    - requests  # TravisCI pytests download test data files too large for github
    - mne >=0.20 # could be an optional dependency but ...

test:
  imports:
    - mkpy

about:
  home: https://github.com/kutaslab/mkpy
  license: BSD
  license_file: LICENSE
