{% set version = "0.2.2" %}
{% set np_pin = "1.16.4" %}
{% set py_pin = "3.6" %}

package:
  name: mkpy
  version: {{ version }}

source:
  # path: ../
  git_url: ../  # to enable GIT_X_Y env vars

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  string: {{ environ.get('GIT_BUILD_STR', "no_tags_on_travis_br") }}

requirements:
  # build ... all moved to host
  host:
    - python ={{ py_pin }}  # else cython uses Python 3.7
    - numpy =={{ np_pin }}
    - Cython

  run:
    - python ={{ py_pin }}  # cythonize with 3.6
    - numpy =={{ np_pin }}  # { pin_compatible('numpy') }}
    - h5py
    - matplotlib
    - pandas
    - pytables
    - pyarrow
    - xlrd
    - PyYAML
    - yamllint
    - pytest  !=5.3.4 # include so users can run tests, bad release fights with nose
    - nose  # for legacy dpath tests

test:
  imports:
    - mkpy

about:
  home: https://github.com/kutaslab/mkpy
  license: BSD
  license_file: LICENSE
